name: mykronicle_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^0.5.10
  toast: ^0.1.5
  otp_text_field: ^1.0.1
  gradient_app_bar: ^0.1.3
  flutter_icons: ^1.1.0
  dotted_border: ^1.0.7
  http: ^0.12.2
  device_info: ^2.0.2
  crypto: ^2.1.3
  html_editor: ^1.0.0
  video_player: ^2.1.14  
  image_picker: ^0.6.4
  html: ^0.14.0+4
  file_picker: ^2.1.7
  path: ^1.8.0
  dio: ^3.0.10
  provider: ^4.3.3
  mime: ^0.9.7
  flutter_colorpicker: ^0.3.5
  webview_flutter: ^0.3.24
  calendarro: ^1.2.0
  auto_size_text: ^2.1.0
  share: ^0.6.5+4
  flutter_downloader: ^1.6.1
  path_provider: ^1.6.28
  permission_handler: ^5.1.0+2
  flutter_image_compress: ^1.1.0
  multi_select_flutter: ^4.0.0
  reorderables: ^0.4.1
  html_unescape: ^1.0.1+3
  flutter_html: ^0.11.0
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  flutter_mentions: ^2.0.1
  flutter_portal: ^0.4.0
  image_cropper: ^1.4.1
  signature: ^3.2.1
  image_painter: ^0.4.4+1
  open_file: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
